spring:
  datasource:
    username: pinboard
    password: password
    url: jdbc:mysql://localhost:3306/pinboard?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: admin
      password: password